In [3]:
import scipy as sp
import numpy as np

In [9]:
from scipy import linalg 

A = np.array([[3,5],[4,6]])
linalg.inv(A)


array([[-3. ,  2.5],
       [ 2. , -1.5]])

In [11]:
# denklem çözümü

# x+3y+5z = 10
# 2x+5y+z = 8
# 2x+3y+8z = 3

A  = np.array([[1,3,5],[2,5,1],[2,3,8]])
B  = np.array([[10],[8],[3]])

print("scipy solution - slow")
print(linalg.inv(A).dot(B))

print("numy solution - fast")
print(np.linalg.solve(A,B))

scipy solution - slow
[[-9.28]
 [ 5.16]
 [ 0.76]]
numy solution - fast
[[-9.28]
 [ 5.16]
 [ 0.76]]


In [13]:
# integral

from scipy import integrate

x = lambda x : x ** 2
I = integrate.quad(x,0,6)
I

(72.00000000000001, 7.993605777301129e-13)

In [19]:
from scipy import special

result = integrate.quad(lambda x : special.jv(2.5, x), 0, 4.5)
result


(1.1178179380783253, 7.866317250224184e-09)

In [26]:
# derivative

from scipy.misc import derivative

def f(x):
    return x**3 + x**2

D = derivative(f, 1.0, dx = 1e-6)
D

4.999999999921734