In [1]:
import numpy as np
import warnings

In [2]:
# wargningleri göstermemek için kullanılır
warnings.filterwarnings("ignore")

In [3]:
# numpy arrays

list1 = [i * 10 for i in range(1,5)]
arr1 = np.array(list1)

print(arr1)
print("type : ", type(arr1))
print("memory location of array : ", arr1.data)
print("data type : ", arr1.dtype)

# int to float
arr1 = arr1.astype(float)
print(arr1)
print(arr1.dtype)

[10 20 30 40]
type :  <class 'numpy.ndarray'>
memory location of array :  <memory at 0x000001F39B3CD4C8>
data type :  int32
[10. 20. 30. 40.]
float64


In [4]:
# np arange

print(np.arange(0,10,2))
print(np.arange(10,0,-2))
print(np.arange(0,10,2).dtype)
print(np.arange(0,10,2).itemsize)
print(np.arange(0,10,2).nbytes)

[0 2 4 6 8]
[10  8  6  4  2]
int32
4
20


In [22]:
print(np.zeros(5))
print(np.ones(5))

# 61den 5 tane
print(np.repeat(61,5))

# repeat eleman bazlı çalıştığı için 10 , 20 ,30 'dan 3er tane 
a = np.array([[10,20,30]])
print(np.repeat(a,3))
print(np.repeat(a,[3],axis=0))

# 5 tane 61
b = np.full(5,61)
print(a)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[61 61 61 61 61]
[10 10 10 20 20 20 30 30 30]
[[10 20 30]
 [10 20 30]
 [10 20 30]]
[[10 20 30]]


In [23]:
# odd and even numbers in np array

arr1 = np.arange(1,20)

odds = arr1[arr1 % 2 == 1]
evens = arr1[arr1 % 2 == 0]

print(odds)
print(evens)

[ 1  3  5  7  9 11 13 15 17 19]
[ 2  4  6  8 10 12 14 16 18]


In [24]:
# np linspace

print(np.linspace(10,20,5))
print(np.linspace(10,20,11))


[10.  12.5 15.  17.5 20. ]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [27]:
# np random

print(np.random.random(4))
print(np.random.randint(0,100,3))

# seed değeri setlenirse random değerler sürekli aynı gelir
np.random.seed(61)
print(np.random.randint(0,100,3))
print(np.random.randint(0,100,3))


[0.49149564 0.55429162 0.23731973 0.6858485 ]
[51 87 48]
[99 18 34]
[16 47 34]


In [28]:
# np uniform

n1 = np.random.uniform(0,10,5)
print(n1)
print(np.floor(n1))

n1 = n1.astype(int)
print(n1)

[4.91495639 5.54291621 2.3731973  6.85848502 9.37769661]
[4. 5. 2. 6. 9.]
[4 5 2 6 9]


In [44]:
# gaussian dist

n2 = np.random.randn(1000)
print("mean : " , np.mean(n2))
print("variance : " ,np.var(n2))
print("standart deviation : " ,np.std(n2))

print("---------------------------------------------")

mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)

print("mean : " , np.mean(s))
print("variance : " ,np.var(s))
print("standart deviation : " ,np.std(s))


mean :  -0.00461335452661976
variance :  1.0471819388605008
standart deviation :  1.0233190796914229
---------------------------------------------
mean :  -0.005066474704306692
variance :  0.009589794639948208
standart deviation :  0.09792749685327512


In [46]:
arr1 = [i*5 for i in range(1,6)]
for index , value in np.ndenumerate(arr1):
    print(index[0] , value)

0 5
1 10
2 15
3 20
4 25


In [47]:
arr = [i*2 for i in range(1,10)]

print("array : " , arr)
print("sum :" , np.sum(arr))
print("cumulative sum : " , np.cumsum(arr))

# min max argmin argmax mean median std variance

print("min : " , np.min(arr))
print("max : " , np.max(arr))
print("argmin : " , np.argmin(arr))
print("argmax : " , np.argmax(arr))
print("mean : " ,np.mean(arr))
print("median : " , np.median(arr))
print("variance : " , np.var(arr))
print("std : " ,np.std(arr))

array :  [2, 4, 6, 8, 10, 12, 14, 16, 18]
sum : 90
cumulative sum :  [ 2  6 12 20 30 42 56 72 90]
min :  2
max :  18
argmin :  0
argmax :  8
mean :  10.0
median :  10.0
variance :  26.666666666666668
std :  5.163977794943222


In [48]:
# np multidimensional arrays

A = np.array([[1,2,-5,4],[7,-2,13,4],[-8,2,9,8],[1,-2,4,7]])
print(A),

print("sum : " , A.sum())
print("max : " , A.max())
print("min : " , A.min()) 

# sutun bazında
print("min value of each columns : " , np.amin(A,axis=0))

# satır bazında
print("min value of each rows : " , np.amin(A,axis=1))

print("mean : ",np.mean(A))
print("mean of columns : ",np.mean(A,axis=0))
print("mean of rows : ",np.mean(A,axis=1))

print("variance : " , np.var(A))
print("variance of columns : " , np.var(A,axis=0))
print("variance of rows : " , np.var(A,axis=1))

print("standart deviation : " , np.std(A))
print("standart deviation of columns : " , np.std(A,axis=0))
print("standart deviation of rows : " , np.std(A,axis=1))


[[ 1  2 -5  4]
 [ 7 -2 13  4]
 [-8  2  9  8]
 [ 1 -2  4  7]]
sum :  45
max :  13
min :  -8
min value of each columns :  [-8 -2 -5  4]
min value of each rows :  [-5 -2 -8 -2]
mean :  2.8125
mean of columns :  [0.25 0.   5.25 5.75]
mean of rows :  [0.5  5.5  2.75 2.5 ]
variance :  27.52734375
variance of columns :  [28.6875  4.     45.1875  3.1875]
variance of rows :  [11.25   29.25   45.6875 11.25  ]
standart deviation :  5.246650717362458
standart deviation of columns :  [5.35607132 2.         6.72216483 1.78535711]
standart deviation of rows :  [3.35410197 5.40832691 6.75925292 3.35410197]


In [49]:
for index, value in np.ndenumerate(A) :
    print(index,value)

(0, 0) 1
(0, 1) 2
(0, 2) -5
(0, 3) 4
(1, 0) 7
(1, 1) -2
(1, 2) 13
(1, 3) 4
(2, 0) -8
(2, 1) 2
(2, 2) 9
(2, 3) 8
(3, 0) 1
(3, 1) -2
(3, 2) 4
(3, 3) 7


In [50]:
a = np.array([1,3,5,8,4,2,9])

print(a[0])
print(a[len(a)-1])
print(a[-1])
print(a[0:4])
print(a[-4:-1])


1
9
9
[1 3 5 8]
[8 4 2]


In [51]:
# np where

arr = np.arange(1,20)

#replace even numbers to 0
a1 = np.where(arr % 2 == 0 , 0 , arr)
print(a1)

arr2 = np.array([10,20,30,10,50])

# replace 10 to 61
a2 = np.where(arr2 == 10 , 61 , arr2)
print(a2)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]
[61 20 30 61 50]


In [52]:
# np put

arr3 = np.arange(0,100,10)
print(arr3)

# replace value of given index to given numbers
# put(array,indexs,numbers)

np.put(arr3 , [0,1,3,7], [61,61,61,61])
print(arr3)

[ 0 10 20 30 40 50 60 70 80 90]
[61 61 20 61 40 50 60 61 80 90]


In [53]:
# missing values

a = np.array([10,np.nan , 11, 54, 61 , np.nan , np.inf , 61 , 41])

print(np.isnan(a))
print(np.where(np.isnan(a)))
print("index of missing values : ",np.where(np.isnan(a))[0])
print("count of missing values : ",len(np.where(np.isnan(a))[0]))

# replace missing values to 16
a[np.isnan(a)] = 16
print(a)

[False  True False False False  True False False False]
(array([1, 5], dtype=int64),)
index of missing values :  [1 5]
count of missing values :  2
[10. 16. 11. 54. 61. 16. inf 61. 41.]


In [54]:
A = np.array([[4,-3,np.nan],[np.nan,np.nan,61],[1,2,3]])

print(A)

print(np.where(np.isnan(A)))
print(np.where(np.isnan(A))[0])
print(np.where(np.isnan(A))[1])

[[ 4. -3. nan]
 [nan nan 61.]
 [ 1.  2.  3.]]
(array([0, 1, 1], dtype=int64), array([2, 0, 1], dtype=int64))
[0 1 1]
[2 0 1]
